import datetime
import csv
class Contacto :
    def __init__( self,NICKNAME,NOMBRE,CORREO,TELEFONO,FECHANACIMIENTO,GASTO):
        self.NICKNAME = ("AlmazaHumb", "Vegetta777", "elRubius", "elORION", "UbaldoLuna04", "Herny", "Hasvik", "Conters", "Lolito")
        self.NOMBRE = ("Humberto Almazan", "Samuel Deluque", "Ruben Doublas", "Jorge Diaz", "Hector Luna", "Guillermo Estrada", "Aldo Rodriuez", "Pedro Aguilar", "Luis Gonzales")
        self.CORREO = ("HordanJordan72@gmail.com", "VegettaGaymer@gmail.com", "Rubierer@gmail.com", "elOrion45@gmail.com", "UbaldoLuna@gmail.com", "hernybreaker@gmail.com", "hasvokhasfrex@gmail.com", "conterstinehok@gmail.com","lolitololo@gmail.com")
        self.TELEFONO = ("8180782627", "8121513875", "8180659395", "8124563087", "8156302489", "8174526302", "8152697025", "8152304792", "8159623048")
        self.FECHANACIMIENTO = ("01/10/2002", "02/02/2000", "19/08/2003", "16/06/2003", "05/04/2001", "24/01/2009", "15/01/2001", "29/02/2001","20/05/2002")
        self.GASTO = ("900.00", "800.00","850.00","200.00","650.00","750","956.00","789.00","600.00")
print("hola")
